 import pygame, math


pygame.image.load("score0-1.png")
pygame.image.load("score0-2.png")
pygame.image.load("score0-3.png")
pygame.image.load("score1-1.png")
pygame.image.load("score1-2.png")
pygame.image.load("score1-3.png")
pygame.image.load("score2-1.png")
pygame.image.load("score2-2.png")
pygame.image.load("score2-3.png")
pygame.image.load("score3-1.png")
pygame.image.load("score3-2.png")
pygame.image.load("score3-3.png")
pygame.image.load("score1-0.png")
pygame.image.load("score1-2.png")
pygame.image.load("score1-3.png")
pygame.image.load("score2-0.png")
pygame.image.load("score2-1.png")
pygame.image.load("score2-3.png")
pygame.image.load("score3-1.png")
pygame.image.load("score3-2.png")
pygame.image.load("score3-0.png")
